sonarqube quality gate test 1

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -124,19 +124,38 @@ jobs:
           cd ./server
           vercel --prod --token ${{ secrets.VERCEL_TOKEN }} -y
 
-  sonarcloud:
-    name: SonarCloud
-    needs: [cypress-tests, jest-tests]
+
+
+  sonarcloud-and-quality-gate:
     runs-on: ubuntu-latest
+    needs: cypress-and-jest-tests
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v2
         with:
-          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
-      - name: SonarCloud Scan
-        uses: SonarSource/sonarcloud-github-action@master
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          fetch-depth: 0
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '14'  # Puedes cambiar la versión de Node.js según tu proyecto
+
+      - name: Install dependencies
+        run: npm install
+
+      - name: SonarCloud Analysis
+        run: |
+          npm run build  # Asegúrate de ajustar este comando a tu proyecto
+          sonar-scanner
+
+      - name: Check Quality Gate
+        run: |
+          quality_gate_status=$(curl -s "https://sonarcloud.io/api/qualitygates/project_status?projectKey=tddlabteam2023_tddlabteam" | jq -r '.projectStatus.status')
+
+          if [ "$quality_gate_status" != "OK" ]; then
+            echo "Quality Gate Failed"
+            exit 1
+          fi
 
   # Jobs for prettier
   prettier:
